### ISSUE TITLE
Queries returning more than 1024 results overflow the buffer

### ISSUE THREAD

**Issue by joewalker** [mozilla/mentat#131]
user=> (qq '[:find ?x :in $ :where [?x _ _]])
    [nil
     #<java.lang.AssertionError@5414ad44 java.lang.AssertionError: Assert failed: No more than 1024 pending puts are allowed on a single channel. Consider using a windowed buffer.

**Comment by rnewman** [comment]
Bulk-closing ClojureScript/Datomish tickets.
