### ISSUE TITLE
Publish package to npm or bower

### ISSUE THREAD

**Issue by chrmod** [mozilla/mentat#143]
To support common development workflows it would be useful to have Datomish being published to some of those javascript package repositories.

**Comment by rnewman** [comment]
There are some known bugs with the packaging step straight to npm, so this isn't quite a matter of just packaging. The bigger issue is what happens to the cljs implementation while we focus on the Rust version; I'm still thinking about that.

**Comment by chrmod** [comment]
Guess a Javascript version running on top of sqlite or other engine make sense for Firefox based applications. Current cljs version doesn't seems to be very stable when used in Firefox addon, will elaborate ore on that in separate issue.

What kind of problems have you experienced with node packing?

**Comment by rnewman** [comment]
The only scenario we test is using Clojure's own dependency system to pull Datomish into https://github.com/mozilla/datomish-user-agent-service. We walked a user through `npm` packaging standalone on Slack, and the packaged output was empty thanks to an apparently buggy configuration — just plain ol' bitrot. It should be easy to fix, it just means that this issue isn't as simple as someone running `npm publish`.

**Comment by ncalexan** [comment]
> It should be easy to fix, it just means that this issue isn't as simple as someone running npm publish.

If I recall, you need to move `target/SOMETHING.js` into `js/` or `node/`... it would take a few minutes to work out the details.  `npm pack` will let you test this locally and figure out what we were thinking.

**Comment by ncalexan** [comment]
> The bigger issue is what happens to the cljs implementation while we focus on the Rust version; I'm still thinking about that.

Perhaps this is a further argument for starting the Rust implementation in a new repository with a new name?  The interested communities are likely to be pretty different.

**Comment by rnewman** [comment]
> If I recall…

Yeah, that's the approach we were taking. I have a half-done commit locally.

> …a new repository with a new name…

My not-yet-written-up proposal is to

- Fork this repo, configure it to have its own issues, and rename the fork, using that fork for continued community-driven ClojureScript development.
- Rename the main repo and merge `rust` to `master`. That preserves old external links (thanks, GitHub!) and issues. Links to specific commits and lines of cljs code will continue to work, thanks to preserved history.
- Clone cljs-specific issues over to the fork, and close them in the main repo.

**Comment by rnewman** [comment]
I'm cleaning up this repo to be Mentat-only — option 2 above. If someone wants to drive forward the ClojureScript implementation under a new name (not Datomish!), it's at a17142673e6826c808fd77e58ca9d004c6db0e84.
