### ISSUE TITLE
Make the EDN parser support the correct tokens for Keyword and Symbol

### ISSUE THREAD

**Issue by joewalker** [mozilla/mentat#154]
Useful links:
https://github.com/mozilla/mentat/pull/149#discussion_r94966318
https://github.com/joewalker/mentat/blob/f609f4f60c3845811a74c40288872d66611b42c6/edn/src/edn.rustpeg#L54
https://github.com/edn-format/edn

**Comment by rnewman** [comment]
Depends on #139, which I should be landing momentarily.

**Comment by joewalker** [comment]
Also depends on #149 which needs rebasing before it can land

**Comment by rnewman** [comment]
I'm about 80% through doing this for `Keyword`.

**Comment by rnewman** [comment]
Fixed by #163. @joewalker, if you get to this before @ncalexan does, feel free to steal the second rubberstamp review!
