### ISSUE TITLE
Contribution ideas

### ISSUE THREAD

**Issue by palango** [mozilla/mentat#155]
I think this project is really interesting as I have some experience with both rust and datomic.

I see that you're still figuring out the basic architecture, but do you have any areas where contributions are appreciated or wanted?

**Comment by rnewman** [comment]
Hi!

There are lots of things still to be done, and (alas) some of those are the basic building scaffolding on which easy contributions hang.

That said, #133 includes a list of "starter projects" — dependency-free work items — and a skeleton of the rest of the work.

You might take a look at those, or you might want to wait a couple of weeks for more structure to exist. At that point there should be a growing list of shovel-ready issues that we'd love your help with.

Feel free to [join us on Slack](http://tofino-slack-invite.mozilla.io/) in `#mentat` if you want a live view of what's going on, too.
