### ISSUE TITLE
Add support for big integers to the EDN parser

### ISSUE THREAD

**Issue by joewalker** [mozilla/mentat#156]
Probably using [num::BigInt](https://rust-num.github.io/num/num/struct.BigInt.html), maybe with something like this in edn.rustpeg

```
use num::BigInt;
...
#[export]
bigint -> Value = b:$( sign? digit+ "N" ) {
    Value::BigInteger(b.parse::<BigInt>().unwrap())
}
```

And we'll probably need to include bigint in the value definition before integer so the parser doesn't assume it's looking at an int.

See also: https://github.com/edn-format/edn#integers

**Comment by jsantell** [comment]
@joewalker this seems to be implemented as edn::types::Value::BigInteger, [is there anything missing here](https://github.com/mozilla/mentat/blob/c6fa14c0c842dac7dfc1126ad7a5cb5794461d32/edn/tests/tests.rs#L66)?

**Comment by joewalker** [comment]
No, I think you're right. I fixed this.
