### ISSUE TITLE
Test EDN parser against leading, trailing, and inter-element whitespace

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#166]
I saw issues parsing ` [1]`, `[1] `, and `[ [1]]`.  These are simplified and from memory, so they may not all fail.  For what it's worth I was using `r#` raw strings, although I don't think that's relevant.

**Comment by joewalker** [comment]
Mostly it should be the case that you just splash "__" around (see https://github.com/mozilla/mentat/blob/a152e6004013fcb5a0a51df5c38f9dad09964cef/edn/src/edn.rustpeg#L141)
