### ISSUE TITLE
Parse more in tx-parser: id-literals and map shorthand notation

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#169]
We need a way to declare temporary IDs.  Datomic uses EDN read syntax like `#db/id [:db.part/db -1]`; DataScript uses negative integers; our CLJ implementation uses a function invocation like `(id-literal :db.part/db -1)`.  (Bare negative integers aren't appropriate for Mentat, since we're going to support parts.)  I'm loathe to add read syntax just for id-literals and instants, but we need _something_.

While we're here, the initial `tx-parser` commit doesn't support the map shorthand; that is, the valid transaction
```edn
[{:db/id ENTID :temp/attr "value"}]
```
is not yet parsed.

**Comment by rnewman** [comment]
> We need a way to declare temporary IDs.
The new Datomic way to do this, given client APIs that can't afford repeated network round-trips to allocate tempids, is to use placeholder strings and make tempids optional.
The transactor knows each place that a string occurs where an entity ID or ident is expected, and transparently allocates one tempid per string.
See <http://blog.datomic.com/2016/11/datomic-update-client-api-unlimited.html> for details.
I suggest supporting tempids in the transact format itself (allowing their programmatic use), and allowing only string 'tempids' in the EDN input.

**Comment by ncalexan** [comment]
@rnewman correctly points out that using string identifiers for tempids is never ambiguous, because we can always differentiate a string from an entid based on the schema.  During the discussion I pointed out that there is an ambiguity: two item lists are overloaded to be lookup-refs (so `[[:db/attr "unique-value"] :db/other "some other value"]]` is valid.

However, there's an ambiguity here.  It's possible to use a lookup-ref as the value for a `:db/valueType :db.type/ref` which is itself `:db/cardinality :db.cardinality/many`!  That conflicts with the shorthand for adding many datoms using a list.  That is, if `:db/attr` has the above characteristics, what does
```
[ENTITY :db/attr [:user/unique-attr :user/some-enum]]
```
mean?  Do you want to process the two-element list as a lookup-ref?  Or do you want to insert two datoms?

**Comment by rnewman** [comment]
I'd be interested to know what Datomic and DataScript do. We can also detect this case and either define a precedence (pick which thing to do), log, or raise an error.

**Comment by ncalexan** [comment]
This is done: #180, #184.
