### ISSUE TITLE
query inputs not applied to attributes in a where form

### ISSUE THREAD

**Issue by cascadian** [mozilla/mentat#173]
Query 1 & 2, below, are logically equivalent, however 1 always return an empty result set and 2 returns the expected result. It seems like inputs don't get applied to the second item in the where form.

### Query 1
``` clj
(d/<q db
      '[:find ?e
        :in $ ?attr
        :where
        [?e ?attr]]
      {:inputs {:attr :foo/bar}})
```

### Query 2
``` clj
(d/<q db
      '[:find ?e
        :in $
        :where
        [?e :foo/bar]])
```

**Comment by rnewman** [comment]
What do you get for

```
(d/<q db [:find ?e :in '$ '?attr :where ['?e '?attr]] {:inputs {:attr (d/entid db :foo/bar)}})
```

?

**Comment by cascadian** [comment]
Thank you! Using `(d/entid db :foo/bar)` fixed it. Changing the query's quoting worked too, but it also worked as originally quoted.

**Comment by rnewman** [comment]
To summarize: this is pretty much #167. We'll do a more comprehensive job in the rewrite. Thanks for the report!
