### ISSUE TITLE
[tx] Implement :db/tx, :db/txInstant in transactor

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#186]
I just didn't get to tracking transaction IDs at all in #170.  This might require #184, depending on how it's implemented, but there are simpler ways to achieve it.

Each transaction gets an extra assertion of the form:
```edn
[[:db/add :db/tx :db/txInstant INSTANT]]
```
where `:db/tx` is the next sequential transaction ID (in the `:db.part/tx` partition), and INSTANT is the transactors local time.  (We'll ignore clock drift for now -- at our own peril.)

**Comment by rnewman** [comment]
Is this done, @ncalexan?

**Comment by ncalexan** [comment]
> Is this done, @ncalexan?

Yep.  Worth linking to https://github.com/mozilla/mentat/issues/225, which tracks allowing the consumer to use `:db/tx` and `:db/txInstant` in the transaction.

**Comment by rnewman** [comment]
OK. Closing this one!
