### ISSUE TITLE
[tx] Support opening and migrating V1 SQL schema stores

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#194]
For simplicity, #170 supports only creating a fresh V2 SQL schema store (and, I suppose, opening it again).

This ticket tracks doing the little bit of work to migrate a V1 SQL schema store forward to V2.

**Comment by rnewman** [comment]
Notably one needs to:

- Bump part range:

https://github.com/mozilla/mentat/blob/master/src/common/datomish/sqlite_schema.cljc#L158

- Transact the new data:

https://github.com/mozilla/mentat/blob/master/src/common/datomish/db_factory.cljc#L84

**Comment by rnewman** [comment]
Concur on closing this as WONTFIX, @ncalexan? Let's just ship 0.1 with its own starting schema version.

**Comment by ncalexan** [comment]
Sure, that's certainly less work :)
