### ISSUE TITLE
Add EDN pretty printer

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#195]
This ticket tracks adding a pretty-printer (potentially, implementing `std::fmt::Display`) for `edn::types::Value`.

If I was to do this, I'd start by understanding how `serde` achieves this, and then whether there's a Rust implementation of Wadler's pretty-printer combinators.

**Comment by ncalexan** [comment]
This is a _[good first bug]_ if you have strong development skills but not necessarily strong Rust skills.

**Comment by ncalexan** [comment]
@jsantell can you bump this up your priority queue?  It's frustrating having 4k of output on one line when dumping these databases :)  Thanks!

**Comment by ncalexan** [comment]
We have a lot of input and output that looks like `[[:db/add ...] [:db/add ...]]`.  It would be nice to give columnar views easily, using (for example) https://github.com/BurntSushi/tabwriter.

**Comment by victorporof** [comment]
As discussed, I'll take this.

**Comment by ncalexan** [comment]
I see https://github.com/freebroccolo/pretty.rs/issues/26 tracking adding some simple documentation.  The examples and tests are more than enough to complete that issue, which would be a great contribution to upstream...
