### ISSUE TITLE
Expose is_keyword, is_vector, is_map, etc on edn::Value

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#197]
Over in #196, @rnewman wants some helper functions to make destructuring `edn::Value` more pleasant.  This ticket tracks adding `is_*` predicates for all the variants, and potentially `as_vector(Value) -> Option<Vec>` and `as_map(Value) -> Option<BTreeMap<Value, Value>`, etc.

We should aim to provide the exact same helper API as [serde json library](https://github.com/serde-rs/json).

**Comment by rnewman** [comment]
Source pointer:

https://github.com/mozilla/mentat/blob/rust/edn/src/symbols.rs
