### ISSUE TITLE
Add helper functions constructing OrderedFloat and BigInt to edn crate

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#198]
Right now, real consumers of `edn::Value` need to import `OrderedFloat` and `BigInt` in order to pattern match `Value` completely.  That means to `extern crate` declarations, which is awkward.  This ticket tracks exposing simple constructors in the `edn` crate.  For example, maybe
```rust
impl Value {
    from_float(x: f64) -> Value { ... }
    from_bigint(x: &str) -> Value { ... }
}
```

**Comment by victorporof** [comment]
I'll have a go at this.
