### ISSUE TITLE
Extract assert_parses_to into a parser utility crate

### ISSUE THREAD

**Issue by rnewman** [mozilla/mentat#200]
We have (or will have) multiple `combine` parsers in the tree:

- tx
- `:find` expressions
- `:where` expressions
- pull expressions.

These involve a number of utilities for both construction and testing. One such — the first — is the `assert_parses_to!` macro in `query-parser/src/parse.rs`.

This macro simplifies some of the boilerplate around running a parser function against input and expecting a certain result.

This ticket tracks extracting this macro into a separate sub-crate, perhaps called "parser_utils", for use elsewhere in the tree.

**Comment by victorporof** [comment]
Will try this out.
