### ISSUE TITLE
[db] Wrap an edn::symbols::NamespacedKeyword rather than a String in db::TypedValue

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#203]
Per https://github.com/mozilla/mentat/pull/171#discussion_r97866454.  Right now, we extract and clone a `String` in `db::TypedValue::Keyword`.  We'd like to keep this kind of data structured as much as possible, but I don't want to do this work for #170 before landing, so I'm tracking it here.

**Comment by ncalexan** [comment]
I think this should be pretty straight-forward.

**Comment by jsantell** [comment]
Blocking on #291, much of the same code
