### ISSUE TITLE
[tx] Handle dangling references

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#210]
What should happen when the datom store starts as
```clojure
[[101 :some/attr value tx]
 [102 :some/ref 101 tx]]
```
and then we transact `[[:db/retract 101 :some/attr value]]`?  The naive retraction leaves a dangling reference to an entid that no longer can be referenced.

If we need to do the equivalent of SQL's `ON DELETE CASCADE`, that's going to increase the cost of transacting, since it's potentially recursive and we need to maintain the authoritative transaction report.

**Comment by ncalexan** [comment]
I don't know what Datomic does in this circumstance.  @rnewman, do you?

**Comment by ncalexan** [comment]
Based on the discussion at https://groups.google.com/forum/#!topic/datomic/e4DvdR9bk2U, it appears that Datomic itself does _not_ ensure that you don't have dangling references.  It's up to the application to use lookup-refs as appropriate.

**Comment by rnewman** [comment]
There are a few reasons why this is this way:

Firstly, it's totally conceptually consistent for an entity to only be the *object* of relations. That is: retracting `[101 :some/attr value tx]` does not invalidate `[102 :some/ref 101]`.

(You might rephrase your question in the reverse, retracting the other datom, and it would be just as meaningful!)

For example, consider an application that tries to figure out who the murderer was in a game of Clue. We record the killing:

```
[102 :clue/killedBy 101]
```

We assert:

```
[101 :clue/preferredMurderWeapon :candlestick]
```

then we later find out that it's not the case, and retract that new datom. We still have an entity that we use over time to refer to the killer: `101` is still the killer of `102`.

Secondly, there is still a hint of the open world assumption in Datomic (even though it includes closed-world querying, `retractEntity`, *et al*). Entities aren't typed, reference attributes don't have defined type domains and ranges, and so on. "Dangling" is only really a concept under the closed world assumption.

Thirdly, Datomic entity IDs escape the store. `101` might be in use externally as the persistent identifier for some concept, be present in some message, *etc.*; that we're retracting the penultimate (or even the ultimate!) known datom that refers to `101` doesn't mean that it's still an entity in the realm of discourse, and more current facts might refer to it in the future. This means we can't reallocate entity IDs.

The concept of a dangling reference — that is, references to an entity ID for which no datoms have that entity in the `e` place — are a problem in *some* uses of Datomic for data modeling: ORMs (in which a dangling reference is equivalent to a dangling pointer) and closed-world relational systems with foreign key constraints (you can't have an order refer to an unknown line item; it's not useful to know that there was an item in the box, but not know what it was).

The Datomic way to enforce that the store remains in one of these valid subsets is to use database functions, as in [this example](http://stackoverflow.com/a/17137200/22003). The functions can apply whatever constraints they wish: failure, cascade, synthesis, *etc.*

**Comment by rnewman** [comment]
Does my comment suffice to close this, @ncalexan?

**Comment by ncalexan** [comment]
I think so.
