### ISSUE TITLE
Expose slicing and indexing on edn Value

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#216]
I'm writing some EDN consuming code, and it would be nice to be able to index an `edn::Value` instance.  If it's `Value::Map`, keys are arbitrary `Value` instances.  If it's a `Value::Vector`, keys are integers or `Value::Integer`.  By necessity this will do a lot of error and range checking.

**Comment by ncalexan** [comment]
@jsantell you might mentor this, given that you did #197.

**Comment by jsantell** [comment]
We discussed that we can iterate over list-type Values with the `as_*()` functions, which also prevent iterating over a non-iterable Value type, as well as needing to return references in slices, so closing this, please re-open if I'm misunderstanding
