### ISSUE TITLE
[edn] Allow hyphen (-) in symbol and keyword names

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#219]
Names such as `:foo-bar` and `:foo-bar/baz-boz` are legal Clojure (and EDN).  I assume this is just an oversight.

The code that needs to be changed is at https://github.com/mozilla/mentat/blob/rust/edn/src/edn.rustpeg#L87; see the more permissive code at https://github.com/mozilla/mentat/blob/rust/edn/src/edn.rustpeg#L78 for suggestions on how to expand this.

The proposed grammar at https://github.com/edn-format/edn/issues/56 may be authoritative here.

**Comment by ncalexan** [comment]
While we're here, it appears that `:foo_bar` is incorrectly parsed as `edn::value::PlainSymbol(edn::symbols::PlainSymbol("_datoms"))`.  Let's fix this while we're in the neighbourhood.

**Comment by victorporof** [comment]
@ncalexan What should `:foo_bar` be parsed as? `Keyword`?

**Comment by rnewman** [comment]
Yes. And `:foo_bar/baz` is a `NamespacedKeyword`.
