### ISSUE TITLE
[tx] Allow [:db/tx :db/txInstant INSTANT] in transaction input

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#225]
Datomic (and the Clojure implementation of Mentat) allow to specify the `:db/txInstant` that the transaction will be applied with by including a datom like
```edn
[[:db/add :db/tx :db/txInstant INSTANT]]
```
(Note that the `:db/tx` is a Mentat addition, although I think Datomic added an equivalent thing recently.)  This requires `INSTANT` to be strictly after the last transaction timestamp and strictly before the current transactor timestamp.

Adding this allows to import data with meaningful timestamps, for example.

**Comment by rnewman** [comment]
I don't believe it's necessary that the timestamp be later than the last transact: multi-master replication demands the opposite. But it's a reasonable restriction to start with.

**Comment by ncalexan** [comment]
Let's make this ticket track also adding arbitrary assertions with the `:db/tx` entity, that is, handling things like
```
[[:db/add :db/tx ATTRIBUTE VALUE]]
```

**Comment by rnewman** [comment]
3bf74593
