### ISSUE TITLE
Use mentat-parser-utils in tx-parser

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#235]
@rnewman and @victorporof have pushed a bunch of shortening macros to the `mentat-parser-utils` crate in #218.  This ticket tracks using the new tools in the `tx-parser` crate (which was written first and should benefit from the new work).

This is a _[good first bug]_ if you know a little Rust.

**Comment by victorporof** [comment]
Are there specific places where you think these macros need to be used, or is this more of a "let's see what can be simplified".

**Comment by ncalexan** [comment]
> Are there specific places where you think these macros need to be used, or is this more of a "let's see what can be simplified"?

Little of both.  I don't know the full scope of things, but I see `def_parser_fn` instances throughout (like at https://github.com/mozilla/mentat/blob/rust/tx-parser/src/lib.rs#L36) and I see `satisfy_map` which might be shortened in a few places (like at https://github.com/mozilla/mentat/blob/rust/tx-parser/src/lib.rs#L54).

**Comment by victorporof** [comment]
Making a note here that @joewalker offered to steal this from me.
