### ISSUE TITLE
Properly handle whitespace for Infinity and NaN

### ISSUE THREAD

**Issue by victorporof** [mozilla/mentat#244]

**Comment by rnewman** [comment]
> Elements are generally separated by whitespace. Whitespace, other than within strings, is not otherwise significant, nor need redundant whitespace be preserved during transmissions. Commas , are also considered whitespace, other than within strings.
> …
> Tokens beginning with `#` are reserved. The character following `#` determines the behavior. The dispatches `#{` (sets), `#_` (discard), `#alphabetic-char` (tag) are defined below. `#` is not a delimiter.
> …
> edn supports extensibility through a simple mechanism. `#` followed immediately by a symbol starting with an alphabetic character indicates that _that symbol_ is a tag.
> …
> Tag symbols without a prefix are reserved by edn for built-ins defined using the tag system. 
> …
> Tags themselves are not elements. It is an error to have a tag without a corresponding tagged element.

So:

- `#` must be followed by (for our purposes) an alphabetic char, and continuing as the production for a symbol. Tags can be namespaced/prefixed, just like any other symbol.
- The tag must be separated from its following element by some amount of whitespace or commas.
- The tag must be followed by an element.

The following are four acceptable float representations inside a set, according to these rules:

```
#{#f 1.0 #f,1.0
#f﻿\t1.0
#f
1.0}
`
