### ISSUE TITLE
Expose api for edn pretty printing at the cli and server

### ISSUE THREAD

**Issue by victorporof** [mozilla/mentat#247]
Is this likely to be useful? 

@ncalexan You mentioned there's edn output you wanted to pretty print. How do you want to do that? 

@jsantell I assume some kind of rest method on the web server would work for the web tooling?

**Comment by jsantell** [comment]
@victorporof I don't think this is helpful for tooling, based off of what we've talked about previously in terms of features. Possibly, a query can respond with the source, but pretty printed, but on the GUI, we'll have codemirror for prettification while typing, and replacing that with the server's pretty printed version would be disorienting, and the line/column numbers in debugging wouldn't match up either, so I'd say atleast not for now

**Comment by ncalexan** [comment]
> @ncalexan You mentioned there's edn output you wanted to pretty print. How do you want to do that?

Hey!  I want pretty output during tests, which I've elaborated upony at https://github.com/mozilla/mentat/issues/220#issuecomment-277807413.

**Comment by victorporof** [comment]
Ok, closing this for now due to not being required yet.
