### ISSUE TITLE
Replace `use ... *` with explicit lists

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#251]
Per https://github.com/mozilla/mentat/pull/249#discussion_r99631181, it's best to be explicit in our import lists.  This ticket tracks auditing any uses of `use ... *` and replacing them with explicit lists where appropriate.

**Comment by joewalker** [comment]
Anyone have thoughts on `pub use ...::*;` in lib.rs?

I'm tempted to think that we should be explicit there too, but I wonder how often we'll want to not export *? Maybe the rule should be to always `pub use ...:*;` in lib.rs?

edn/src/lib.rs says:

    pub use self::types::Value;
    pub use self::symbols::{Keyword, NamespacedKeyword, PlainSymbol, NamespacedSymbol};

But that's the complete list things for export from each module.

**Comment by joewalker** [comment]
I started to hack on this, but very happy to drop it if someone else wants to pick it up.

**Comment by ncalexan** [comment]
> Anyone have thoughts on pub use ...::*; in lib.rs?
> 
> I'm tempted to think that we should be explicit there too, but I wonder how often we'll want to not export *? Maybe the rule should be to always pub use ...:*; in lib.rs?

Perhaps `lib.rs` is the _most_ valuable place to be explicit, since it's the master list, the central source of truth.

**Comment by jsantell** [comment]
Whatever reason there is to use `use ...::*`, it will have to be more valuable than the detriment to newbie rust users and those new to contributing to Mentat, because magic variables where it's not explicit where they come from (without tooling) are awful. I'll check this out.
