### ISSUE TITLE
[db] Run pragmas to configure SQLite store and connection when we open a DB

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#259]
This ticket tracks running SQLite pragma commands when we open a database, just like we do in the Clojure implementation.  See https://github.com/mozilla/mentat/blob/84a80f40f5c888f8452d07bd15f3b5fba49d3963/src/common/datomish/db_factory.cljc#L126.

We should make the `new_connection` function around https://github.com/mozilla/mentat/blob/c585715224c180ff84630c05aa763d0d271f350a/db/src/db.rs#L23 accept a URI (so it can handle file-backed and in-memory databases), and then run the pragmas in that function.

**Comment by victorporof** [comment]
Where would the URI come from for new_connection? CLI? Or are there no consumers for that function yet? (which my quick grep would seem to indicate).

**Comment by ncalexan** [comment]
> Where would the URI come from for new_connection? 

As a parameter.

> CLI? Or are there no consumers for that function yet? (which my quick grep would seem to indicate).

I think we use it in tests, but we only want in-memory DBs in tests so it's a little artificial.  SQLite has a special "file::memory:" URI for in memory (see https://www.sqlite.org/inmemorydb.html) so there's no loss doing it this way.  Eventually we'll want to open on disk DBs, and some older tests did that.

Eventually, the CLI will plumb a filename through to this -- and you could start wiring this up, connecting the CLI to DB, if you wanted.
