### ISSUE TITLE
[db] Convert Schema into edn::Value for pretty-printing, debugging, etc

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#260]
Mentat stores its `Schema` in an optimized representation, where keys are integer entids and attributes are represented by `Attribute` structures with bit flags.  It's not easy to read, and it's definitely not easy to transact back against an existing store, or compare to Datomic schemas.

This ticket tracks converting `Schema` into `edn::Value`.  The output will be a map that looks something like the "symbolic schema" defined in the bootstrapping code around https://github.com/mozilla/mentat/blob/c585715224c180ff84630c05aa763d0d271f350a/db/src/bootstrap.rs#L86, i.e.:
```edn
{ :db/attribute
  { :db/valueType :db.type/long
    ...
  }
  ...
}
```
I don't think this will be common enough to warrant a `From`/`Into` implementation -- just a `Schema.as_edn_value(&self) -> edn::Value` should be enough.

**Comment by victorporof** [comment]
Assigning to hopefully learn something about the db crate.

**Comment by ncalexan** [comment]
> Assigning to hopefully learn something about the db crate.

Sure!  @jsantell filed #268, which would be much easier with this function, so it might be worth getting feedback from him and doing that as a consumer of this.

**Comment by fluffyemily** [comment]
Can I just confirm the exact output that you want here.

I read this as, given a schema with an attribute with ident `NamespacedKeyword { namespace: "foo", name: "bar" }` and attribute `{ value_type: Boolean, multival: false, unique: None, index: false, fulltext: false, component: false }` should the output be this?:

```
{ :db/attribute
    { :db/id                :foo/bar
      :db/valueType  :db.type/bool
      :db/cardinality  :db.cardinality/one}
}
```
and for ident `NamespacedKeyword { namespace: "foo", name: "baz" }` and attribute `{ value_type: Ref, multival: true, unique: Some(attribute::Unique::Value), index: true, fulltext: true, component: true }` should the output be this?:

```
{ :db/attribute
    { :db/id                   :foo/baz
      :db/valueType      :db.type/ref
      :db/cardinality      :db.cardinality/many
      :db/unique            :db.unique/identity
      :db/indexing         true
      :db/fulltext            true
      :db/isComponent true }
}
```

and, I'm sorry, but I am a little confused how to chain them together, with multiple attributes in the same schema. to give a single output for a large schema.

**Comment by rnewman** [comment]
As an example, you're trying to produce something like the value of the `:schema/attributes` entry in

https://github.com/mozilla/mentat/wiki/Proposal:-application-schema-coordination-and-versioning#an-example

**Comment by ncalexan** [comment]
> Can I just confirm the exact output that you want here.

Modulo Richard's comments, this looks good.  Two wrinkles:
- schema elements can be anonymous.  That is, a key in `schema_map` is not necessarily a key in `entid_map`.  Might as well just let those be integer entid keys in the output map, or follow Richard's approach of producing a vector where some of the inner maps do not include `:db/id` [1].
- it would be nice to not include the defaults for attributes.  That is, don't include `:db/fulltext false`.  The reason for this is subtle and has to do with how we store the materialized "schema" view and how we might handle _new_ attribute characteristics in the future.  If we assume everything is fully specified, we can't easily add a new characteristic (say, a `:db/hashWith` or something like that) with particular defaults.

[1] Why `:db/id` and not `:db/ident`?  'cuz `:db/id` has special meaning in nested maps to the transactor; see the "Nested maps in transactions" section of http://docs.datomic.com/transactions.html.
