### ISSUE TITLE
[tests] Use the EDN matcher for testing transaction output

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#271]
In #214, I implemented the first parts of #188, which tracks converting Clojure implementation tests into generic EDN format tests that could run against the Clojure implementation and the Rust Mentat implementation.

As I say in #188:

> It might be finicky to get the transaction IDs, timestamps, and other ephemeral data correct. I wonder if we can rewrite :db/tx and :db/txInstant in controlled locations to get what we want?

And that's what I did in #214: I translated transaction IDs and certain timestamps into `edn::Value::Symbol` instances like `?txN` and `?msN`, and then compared the resulting EDN with test EDN using the same symbols.  That is, _after_ reading from the store I post-processed the transaction assertions and datom assertions, etc, looking for particular patterns and combinations to rewrite.

This ticket tracks doing something more general.  I'd like to be able to take arbitrary EDN and _pattern match_ it against EDN, without having to postprocess.  I want to handle a few things:
- `_` matches arbitrary sub-EDN;
- `?name` matches sub-EDN, which must be identical each place `?name` appears;
- `...` matches arbitrary sibling-EDN

For example:
- `[_]` matches an arbitrary one-element vector
- `[_ _]`matches an arbitrary two-element vector
- `[?x ?x]` matches `[1 1]` and `[#{} #{}]` but not `[1 2]` or `[[] #{}]`
- `[1 ...]` matches `[1]` and `[1 1]` and `[1 2 3]`, but not `[2]` or `[2 1]` or `#{1 2}`.

Note that `...` is a valid EDN symbol.  Sibling EDN is a little tricky because it needs to handle un-ordered sets and maps, but I think it's do-able.

This is a particularly useful case of a structural EDN differ, as discussed in #220.

**Comment by ncalexan** [comment]
This is a fun ticket if you know some Rust, but it's probably not a great first bug.  It's a good second bug, though!

You'll want to update:
-  the test harness around https://github.com/mozilla/mentat/blob/42580539b8a58f9d10e5891a22112f8c1b697bff/db/src/db.rs#L891 to use your new differ;
- the debug utilities that the harness uses to not post-process; see https://github.com/mozilla/mentat/blob/42580539b8a58f9d10e5891a22112f8c1b697bff/db/src/debug.rs#L130;
- the text data itself around https://github.com/mozilla/mentat/tree/42580539b8a58f9d10e5891a22112f8c1b697bff/tx/fixtures;
- the Wiki page documenting the test format at https://github.com/mozilla/mentat/wiki/Transacting:-EDN-test-format

**Comment by ncalexan** [comment]
And... I just hit my first real-world use case where I want this.  Concretely, I'm testing a "complex upsert" of the form
```edn
[["t1" :db.schema/attribute "t2"]]
```
The resulting transaction includes an assertion like
```edn
[65536 :db.schema/attribute 65537]
```
with newly allocated entids.  It would be great to be able to match those (with `?eN`, say) and verify we're getting new entids, etc.  (In this case, it's hard to say anything _about_ the `?eN`, but it would good to check the form at least.)

**Comment by victorporof** [comment]
@ncalexan There's a relatively important issue here where the patterns agreed upon cannot themselves be matched as if they were actual symbols in the matched edn. For example, agreeing that `_` matches arbitrary subtrees would mean that having an explicit match for a `_` symbol would be impossible. Similar issue for `...` and `?foo`.

If this is something we care about, there seems to be a need for explicitly distinguishing edn values from patterns. Extending the edn spec with `#p pattern` rules, and perhaps some clear `Pattern` type? This might be overcomplicating things, but we're otherwise clearly limiting the matcher's capabilities.

**Comment by ncalexan** [comment]
> @ncalexan There's a relatively important issue here where the patterns agreed upon cannot themselves be matched as if they were actual symbols in the matched edn. For example, agreeing that _ matches arbitrary subtrees would mean that having an explicit match for a _ symbol would be impossible. Similar issue for ... and ?foo.

Yep, understood.  This is conceptually like "quoting", but in the EDN.  I'm happy to just leave this for now, file follow-up, and work out something else later if it's necessary.

**Comment by ncalexan** [comment]
If you really want to leave this open for generalization, add a trait like:
```rust
trait PatternMatching {
    /// Return true if the given pattern matches an arbitrary value.
    fn matches_any_value(pattern: edn::Value) -> bool;
    /// Return true if the given pattern should match arbitrary sibling values.
    fn matches_any_siblings(pattern: edn::Value) -> bool;
    /// Return a symbol and value if the given pattern matches a placeholder.
    fn matches_placeholder(pattern: edn::Value) -> Option<(edn::Symbol, edn::Value)>;
}
```
then you can implement `DefaultPatternMatching` on some placeholder type, which just compares to `_`, `...`, and `?name` as appropriate.

**Comment by victorporof** [comment]
@ncalexan On what kind of "placeholder" type would this trait be implemented? I'm having a hard time understanding what exactly you mean by this? A placeholder for some `edn::Pattern`? `edn::Value`? I don't see how traits fit into the equation.

**Comment by victorporof** [comment]
@ncalexan The `matches_any_siblings` function seems to be tricky to implement due to the fact that edn values have no concept of ancestors nor siblings (even though edn values are basically tree structures). The signature should either accept some "parent" value, or be something like `matches_some_children` or similar, unless I'm misunderstanding everything.

**Comment by ncalexan** [comment]
> @ncalexan On what kind of "placeholder" type would this trait be implemented? I'm having a hard time understanding what exactly you mean by this. A placeholder for some edn::Pattern? edn::Value? I don't see how traits fit into the equation.

I see now all the trait methods should take references; with that change:
```rust
struct DefaultPatternMatching;
impl PatternMatching for DefaultPatternMatching {
    fn matches_any_value(pattern: &edn::Value) -> bool {
        pattern == &edn::Value::Symbol("_".into()) // May need some changes to actually make a `Symbol`.
    }
    ...
}
```
and then something like:
```rust
impl edn::Value {
    pub fn matches(pattern: edn::Value, using: P) where P: Into<Option<PatternMatching>>> -> MatchDetails {
        let using = using.into().unwrap_or(DefaultPatternMatching);
        ...
    }
}
```

**Comment by ncalexan** [comment]
> @ncalexan The matches_any_siblings function seems to be tricky to implement due to the fact that edn values have no concept of ancestors nor siblings (even though edn values are basically tree structures). The signature should either accept some "parent" value, or be something like matches_some_children or similar, unless I'm misunderstanding everything.

Aye, I agree.  You can not handle it, at least at first.  But if I was doing this, I'd check for the special siblings pattern whenever I saw a collection in the pattern, and adjust accordingly.  That is, you'd switch to set containment rather than equality, or vector prefix rather than equality.  (For maps, I see that we really want `... ...` so that the pattern still has a key-value pair in the relevant map.)

This is obviously less efficient, but it's probably not significant.  If you wanted to be more efficient, you could do some kind of backtracking when you see a siblings pattern.  This might be sensible if instead of just bailing out when the pattern doesn't match, you build some kind of `MatchDetails` (like I hint at above) that collects all the different places the match fails.  Then when you see the siblings patterns, you pop pieces of the details off, or otherwise re-evaluate in light of the new pattern details.

You could also say that for ordered patterns (vector and list) the siblings pattern must be the _last_ child value, which makes it easier to know if you're handling this case.  (In the unordered cases, you can just check if the value is present (set) or the key is present (map)).  You probably want to fail for patterns that repeat the sibling pattern, too, since that's likely an error.

**Comment by victorporof** [comment]
@ncalexan Consider another issue: `#{1 _ _}` cannot match `#{1 2 3}` because sets guarantee uniqueness of values, and since `_` is just a symbol, the first set will have a length of 2, while the second one will have a length of 3. This results in a rather leaky abstraction when it comes to pattern rules. I guess this too can be handled in a followup, but we should get our escaping story straight.

**Comment by victorporof** [comment]
@ncalexan Same story for maps: `{1 2, _ 4, _ 6}` cannot match `{1 2, 3 4, 5 6}`.

**Comment by ncalexan** [comment]
> @ncalexan Consider another issue: #{1 _ _} cannot match #{1 2 3} because sets guarantee uniqueness of values, and since _ is just a symbol, the first set will have a length of 2, while the second one will have a length of 3. This results in a rather leaky abstraction when it comes to pattern rules. I guess this too can be handled in a followup, but we should get our escaping story straight.

Ooh, you're right, good catch.  Even marking patterns with `#p _` might not address this, since it would be unusual to make a returned `Pattern _` object not match another `Pattern _`.  It could be made to work, but you're right, this isn't possible with this approach.

**Comment by victorporof** [comment]
@ncalexan One could imagine naming the `_`s, maybe having some sort of generalized `?placeholder` that matches anything. But indeed, this is getting a bit ungodly. Is having `#p _` create unique placeholders such a bad idea?

**Comment by ncalexan** [comment]
> @ncalexan One could imagine naming the _s, maybe having some sort of generalized ?placeholder that matches anything. But indeed, this is getting a bit ungodly. Is having #p _ create unique "any-placeholders" such a bad idea?

Great minds think alike.  I don't feel too strongly about `#p _` creating _unique_ placeholders, but I do think that using the # syntax is something we shouldn't do lightly, since it hacks up the parser for things that aren't general EDN.  That is, the parser doesn't yet support # syntax in general, so we'd need to change the `Value` type.

**Comment by victorporof** [comment]
Repurposed this issue for actually using the edn matcher added in #338

**Comment by ncalexan** [comment]
As I do some of this conversion, I'm finding that for maps, `... ...` is the norm.  That is, I almost always want to specify a sub-map pattern, not the complete map.  Perhaps we should "invert the relationship for map", and make a different sigil mean "exact map" and the regular pattern mean "submap".  Perhaps use `.` to "close" the map, so that
```edn
{:key :value
 . .}
```
means exactly one key (`:key`).  However, that notation looks horrid.  Does anyone have anything better?
/cc @joewalker @victorporof

**Comment by ncalexan** [comment]
Perhaps it would be better to be explicit in the patterns, so
```edn
(= {:key :value})
```
and
```edn
(<= {:key :value})
```
for exact and submap relations.  That has the advantage of also allowing `(>= {:key :value})`... and also allowing arbitrary other computations.  This is starting to feel like a time sink, so I'd like to gently redirect to tickets like #284, #183, #180, etc.

**Comment by rnewman** [comment]
> Perhaps use `.` to "close" the map

Well, `{. .}` is a perfectly legitimate map from one symbol to another!

And what if you want to include negation: the input map must contain keys `A` and `B`, can contain other keys, but must not contain `Z`?

I think once again this comes down to: you need to separate out the comparison pathway from the inputs. It's too confusing to try to jam an arbitrary tree structure, possibly with multiple conditions at each point, into an ordinary data structure.

Total strawman, but:

```edn
{:is :array
 :size (> 10)
 :contains #{1 5 {:is :set :size 5}}   ; Contains two integers and a large set.
 :excludes #{6}}
```

and simpler versions like:

```
{:is :array
 := [1 5 9]}
```

seems like a reasonable recipe, if you're completely wedded to doing this in data structures rather than code.

**Comment by ncalexan** [comment]
> if you're completely wedded to doing this in data structures rather than code.

I'm not.  The more we explore this, the worse an idea it seems, so let's stop pushing on this approach.  I'll try to express the existing tests in code and we'll move forward from there.
/cc @joewalker
