### ISSUE TITLE
[edn] Support hexadecimal, octal, and Java-style base 2-36

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#277]
So, another place where EDN's lacking specification requires additional digging.  It appears that EDN supports:
- hexadecimal with prefix `0x`
- octal with prefix `0`
- Java-style base 2-36, with prefix `Br` or `BBr`, like `2r11` (which is `3`) or `36r11` (which is `37`)
This ticket tracks making our EDN parser handles these esoteric inputs.  (I really only care about hex, which causes strange values to be returned from our parser right now.)

I found the following link where Hickey says this is what Clojure supports: https://groups.google.com/d/msg/clojure/arArR1UJox0/vS1Qofh2ftUJ.

I found the following link where this should be discussed, but isn't: https://clojure.org/reference/reader.

I tested locally using the suggestions from https://clojuredocs.org/clojure.edn/read; like:
```clojure
user=> (require '[clojure.java.io :as io] '[clojure.edn :as edn])
nil
user=> (edn/read (java.io.PushbackReader. (io/reader (.getBytes "0x10"))))
16
user=> (edn/read (java.io.PushbackReader. (io/reader (.getBytes "2r10"))))
2
user=> (edn/read (java.io.PushbackReader. (io/reader (.getBytes "2r11"))))
3
user=> (edn/read (java.io.PushbackReader. (io/reader (.getBytes "011"))))
9
```

**Comment by ncalexan** [comment]
This is a good first bug.  Start digging into our PEG grammar around https://github.com/mozilla/mentat/blob/9be487ca7d84416f71c8c77361c9483f7bccc88f/edn/src/edn.rustpeg#L54.

**Comment by jsantell** [comment]
I'll check this out -- is there a need to retain the original representation or would `2b11` just be `Integer(3)`?

**Comment by ncalexan** [comment]
On Thu, Feb 9, 2017 at 4:42 PM, Jordan Santell <notifications@github.com>
wrote:

> I'll check this out -- is there a need to retain the original
> representation or would 2b11 just be Integer(3)?
>
The latter, no need to retain the original text.  (A different ticket, the
one about EDN input spans, would address that.)
