### ISSUE TITLE
[tx] Accept vector values for :db/cardinality :db.cardinality/many attributes

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#284]
Datomic accepts a shorthand for asserting many assertions with the same `[e a]` values, where the attribute is `:db.cardinality :db.cardinality/many`.  A transaction of the form
```edn
[[:db/add ENTITY :many-attribute [V1 V2 V3]]
```
is equivalent to
```edn
[[:db/add ENTITY :many-attribute V1]
 [:db/add ENTITY :many-attribute V2]
 [:db/add ENTITY :many-attribute V3]]
```
See http://docs.datomic.com/transactions.html, "Cardinality many transactions".  (Note that such shorthand is valid for `:db/retract` as well as `:db/add`.)

This ticket tracks rewriting terms with vector values into many terms with scalar values.  The relevant code is around https://github.com/mozilla/mentat/pull/283/commits/23ea4c9604cab4d45be4b8a3961667394433d7e1#diff-54794907269c3b2d0bebbfd6a8aeab5dR895.

There are a few wrinkles:
- Vectors could be nested.  It stands to reason that `[V1 V2 [V3 V4]]` would flatten all the way down to `[V1 V2 V3 V4]`  It's almost certainly a mistake in human input, but it's convenient to handles values uniformly in generated input.  I have no strong feelings about this and am inclined to flatten vectors entirely.  (Lists and sets should be rejected, just for hygiene.)  However, this might interact with the next thing...
- Vectors of length 2 can have special meaning: they can be _lookup refs_ (see http://docs.datomic.com/identity.html#lookup-refs).  There's going to be some special work needed to disambiguate lookup refs from vectors of length 2 around https://github.com/mozilla/mentat/pull/283/commits/23ea4c9604cab4d45be4b8a3961667394433d7e1#diff-54794907269c3b2d0bebbfd6a8aeab5dR898, and in general it can't be done: if an assertion is
  ```edn
  [:db/add e :many-ref-attribute [a v]]
  ```
  where `:many-ref-attribute` is `:db.valueType :db.type/ref` and `:db/cardinality :db.cardinality/many`, _and_ `a` and `v` are given as numeric entids or keyword idents, there's no way to distinguish the two cases.

In neither of the situations above do I know what Datomic does or how they try to disambiguate.  In the Clojure implementation, I made callers annotate lookup refs like
```edn
[:db/add (lookup-ref a v) :other-atttribute v]
```
to disambiguate.  (We could do that here but I'd like to use Rust's stronger type system to not require this manual disambiguation.)  For now, let's assume that **vectors of length 2 are always lookup refs if they can be** and see where that gets us.

This depends on https://github.com/mozilla/mentat/pull/283, so it's not ready to work on yet.

**Comment by rnewman** [comment]
I'm inclined to suggest something like: a two-element vector in the value position should be interpreted as two values, and nested lists of items are not allowed.

That allows us to unambiguously equate:

```
[:db/add e a [x y]]
```

to

```
[:db/add e a x]
[:db/add e a y]
```

and

```
[:db/add e a [[x y]]]
```

to

```
[:db/add e a (lookup-ref x y))]
```

Thoughts?

**Comment by ncalexan** [comment]
> Thoughts?

I'd be fine with this, although I don't think it agrees with Datomic.  Figuring out what Datomic does would be a valuable first step for this ticket.

**Comment by ncalexan** [comment]
@joe this is a good bug to start with in the transactor.

**Comment by joewalker** [comment]
Above:
> This ticket tracks rewriting terms with vector values into many terms with scalar values. The relevant code is around https://github.com/mozilla/mentat/pull/283/commits/23ea4c9604cab4d45be4b8a3961667394433d7e1#diff-54794907269c3b2d0bebbfd6a8aeab5dR895.

Force pushes rotted the link, are we talking about https://github.com/mozilla/mentat/blob/5e3cdd1fc2a52396837a0018522c75a144f0776c/db/src/upsert_resolution.rs#L90-L125?

**Comment by joewalker** [comment]
Similar vein:

> There's going to be some special work needed to disambiguate lookup refs from vectors of length 2 around https://github.com/mozilla/mentat/pull/283/commits/23ea4c9604cab4d45be4b8a3961667394433d7e1#diff-54794907269c3b2d0bebbfd6a8aeab5dR898,

Except this time I'm feeling lazy - do you have an un-rotted link?
