### ISSUE TITLE
Use sqlite3_limit instead of SQLITE_MAX_VARIABLE_NUMBER

### ISSUE THREAD

**Issue by rnewman** [mozilla/mentat#288]
This was [recently implemented in rusqlite](https://github.com/jgallagher/rusqlite/pull/221).

We shouldn't hard-code `999` in `db/src/lib.rs`; we should instead call `sqlite3_limit` each time we use (or acquire, if we never change the limit) a connection.

This is a good first bug. Do the following:

- Make sure our dependencies on `rusqlite` throughout all of our `Cargo.toml` files match a version of rusqlite that supports the needed functionality.
- Find uses of `SQLITE_MAX_VARIABLE_NUMBER` and replace them with calls to `sqlite3_limit`.
- Delete the constant.

**Comment by victorporof** [comment]
I'll have a go to learn about rusqlite.

**Comment by victorporof** [comment]
I've been waiting for rusqlite to tag a stable version which has this. As it stands, the latest 0.9.5 doesn't expose the API for limits yet, so it would seem that we still have to wait for a little while longer. Unassigning for now.
