### ISSUE TITLE
Convert Schema IdentMap to use NamespacedKeyword

### ISSUE THREAD

**Issue by rnewman** [mozilla/mentat#291]
This should be started on top of #290.

Currently, we use `String`, like `:db/ident`. We should instead use `NamespacedKeyword` — that's what we'll have in hand when we come to do ident lookups, and it's expensive and silly to have to concat up a string just to do a lookup in a map.

This is a really straightforward issue.

**Comment by rnewman** [comment]
This will involve touching `IdentMap`:

```
/// Map `String` idents (`:db/ident`) to positive integer entids (`1`).
/// TODO: these should all be parsed into NamespacedKeywords on entry.
pub type IdentMap = BTreeMap<String, Entid>;
```

and its call sites.

**Comment by ncalexan** [comment]
This is related to #203.  We should enlarge the scope of this ticket: we really want to accept `Keyword` _and_ `NamespacedKeyword` throughout `TypedValue` and `Schema`; right now we achieve that through `String`, but we should do it by accepting either type of keyword.  This might be best handled with an enum in `tx` or `core`; or it might be best handled by unifying `edn::symbols::{Keyword,NamespacedKeyword}` into an enum and using that throughout.  I expect the latter but haven't investigated yet.

**Comment by rnewman** [comment]
#290's in, so this is ready to go.

**Comment by rnewman** [comment]
All current and supported schema items are namespaced keywords, right? If so, another (and reasonable) approach is to switch to `NamespacedKeyword` then morph to include `Keyword` later if desired.

**Comment by ncalexan** [comment]
> All current and supported schema items are namespaced keywords, right? If so, another (and reasonable) approach is to switch to NamespacedKeyword then morph to include Keyword later if desired.

Yes, I concur.  @rnewman also reminded me that he and I initially discussed and agreed upon _only_ accepting namespaced keywords for vocabulary (attribute idents), negating most of https://github.com/mozilla/mentat/issues/291#issuecomment-279593220.  This is different than Datomic, which accepts plain keywords but recommends against it.

So let's just migrate to `NamespacedKeyword` for now, and continue not allowing plain keywords for attribute idents.  /cc @jsantell
