### ISSUE TITLE
[query] Type code expansion

### ISSUE THREAD

**Issue by rnewman** [mozilla/mentat#293]
As we process a collection of patterns into a CC, we collect constraints. For example,

```edn
[?x ?a true]
```

yields a constraint like

```
ColumnConstraint::EqualsValue(d0_v, TypedValue::Boolean(true))
```

Some types (including boolean) share a SQLite value representation with other types — `1` could be a ref, an integer, an FTS string, or a boolean.

This ticket tracks expanding appropriate `value_type_tag` constraints out of a set of column constraints once all value constraints are known. We naturally must wait until _all_ value constraints are known, because `?a` might later be bound, which will eliminate the need to constrain `value_type_tag`.

It's possible at this point for the space of acceptable type tags to not intersect: _e.g._, the query

```edn
[:find ?x :where
 [?x ?y true]
 [?z ?y ?x]]
```

where `?y` must simultaneously be a ref-typed attribute and a boolean-typed attribute, which is impossible. This function should deduce that and call `ConjoiningClauses.mark_known_empty`.

See also #292.

**Comment by fluffyemily** [comment]
Can I clarify I need to do 3 things here.
1. Identify all constratins with ambiguous values and add `value_type_tag` constraints to clarify.
2. Identify all constraints with values assigned that do not match their `known_type` and `mark_known_empty`.
3. Identify all `extracted_types` and add `value_type_tag` constraints.

**Comment by rnewman** [comment]
There are three kinds of queries that you need to make behave.

The first is a join between type-ambiguous values.

```
[:find ?x ?y ?z
 :where
 [?x _ ?y]
 [?z _ ?y]]
```

— `?y` could be anything, so we not only need `datoms00.v = datoms01.v`, but we also need `datoms00.value_type_tag = datoms01.value_type_tag`. We know all of those columns in `column_bindings`, and we expand those in `expand_column_bindings`; you need to do a similar thing when you fill out `expand_type_tags`.

The second is a join between ambiguous and unambiguous.

```
[:find ?x ?y ?z
 :where
 [?x _ ?y]
 [?y _ ?z]]
```
— here `?y` must be `ValueType::Ref`, so we need to generate `datoms00.value_type_tag = 1 AND datoms00.v = datoms01.e`. I'm not sure if a place for this already exists: after all, we think that `?y` is unambiguous, but we won't be filtering the first table correctly.

The third is a type-imposing constraint.

```
[:find ?x ?v
 :where
 [?x _ ?v]
 [(< ?v 10)]]
```

— here we know that `datoms00.value_type_tag = 5`, because `?v` must be numeric. I think we do this already.

To speak to your three-item list: I think we already do all of (2) and some of (1). (3) isn't always a certainty. If we know the attribute of a pattern — or, more generally, we know that a particular pattern can never yield values of the wrong type, either because of the attribute column or because of some magical other knowledge we might have — then we don't need to limit on type.

**Comment by rnewman** [comment]
My recommendation is to write tests for those, and see which ones pass!

**Comment by fluffyemily** [comment]
for case 
```
[:find ?x ?y ?z
 :where
 [?x _ ?y]
 [?z _ ?y]]
```
 We need to add the `datoms00.value_type_tag = datoms01.value_type_tag` as the other is already done. What I have in place so far achieves this, so yay! me.

for case 
```
[:find ?x ?y ?z
 :where
 [?x _ ?y]
 [?y _ ?z]]
```
We need to add `datoms00.value_type_tag = 1`. This is not being handled by my new code so far so will add this case.

for case
```
[:find ?x ?v
 :where
 [?x _ ?v]
 [(< ?v 10)]]
```

we get this output currently

```
ConjoiningClauses { 
    empty_because: None, 
    from: [SourceAlias(AllDatoms, all_datoms00)], 
    wheres: [Constraint(all_datoms00.v < value(Long(10)))], 
    column_bindings: {var(?v): [all_datoms00.v], var(?x): [all_datoms00.e]}, 
    input_variables: {}, 
    value_bindings: {}, 
    known_types: {var(?v): ValueTypeSet({Long, Double}), var(?x): ValueTypeSet({Ref})},  
    extracted_types: {var(?v): all_datoms00.value_type_tag} 
}
```

I am a little confused here. If we know that `?v` is numeric, then we should be referencing `datoms` rather than `all_datoms` shouldn't we? I thought `all_datoms` was just for when we didn't know the type? Is this a bug?

**Comment by rnewman** [comment]
That's #385; you can skip it for now.
