### ISSUE TITLE
[query] Algebrize `not` patterns

### ISSUE THREAD

**Issue by rnewman** [mozilla/mentat#302]
After parsing these in #239, we need to build a simple wrapper around a CC to denote negation.

`not-join` is the simplest extension: it's simply a set of patterns (which we term a CC) and a list of variables to unify with the enclosing query.

**Comment by fluffyemily** [comment]
https://github.com/mozilla/mentat/commit/bd389d2f0de395ef1bc46ea4363def098e2bd687
