### ISSUE TITLE
[query] Translate `not` patterns

### ISSUE THREAD

**Issue by rnewman** [mozilla/mentat#303]
On top of #301 and #302, translating a `not-join` to SQL involves one of two branches:

* If the enclosed CC doesn't generate any bindings, then it can simply be an expression negating the CC's `wheres`:

    ```
    NOT (datoms123.e = 456 AND …)
    ```

* If the enclosed CC does generate bindings, then we must generate a subquery:

    ```
    NOT EXISTS (SELECT …)
    ```

This ticket will reuse a lot of code from #301, and will make it clear whether the abstractions in that ticket were well chosen!

**Comment by fluffyemily** [comment]
https://github.com/mozilla/mentat/commit/bd389d2f0de395ef1bc46ea4363def098e2bd687
