### ISSUE TITLE
[query] Intern variables to avoid extensive cloning

### ISSUE THREAD

**Issue by rnewman** [mozilla/mentat#318]
We use `Variable` as a key into maps and more. We should use `Rc` and an `InternedSet` to avoid the need to clone.

**Comment by ncalexan** [comment]
To flesh this out a little bit, there's cloning in the initial algebrizer landing throughout the conversion to clauses; start looking around https://github.com/mozilla/mentat/blob/5af7082165061f530dd77f14a13196230cce5c34/query-algebrizer/src/cc.rs#L467.

What we'd like to do is use an `InternSet<Variable>` to avoid cloning these strings.  There's a not-quite-complete example of how this works in the transactor: start reading around https://github.com/mozilla/mentat/blob/5af7082165061f530dd77f14a13196230cce5c34/db/src/tx.rs#L139.

**Comment by rnewman** [comment]
`Variable` is now a newtype of `Rc<PlainSymbol>`, so we're most of the way there. Closing.
