### ISSUE TITLE
[core] Use combine 2.3.0 to simplify ValueParseError

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#343]
After #341, we'll have a `ValueParseError` in `mentat_parser_utils`.  This can be simplified using the new functions in https://github.com/Marwes/combine/pull/87, released in `combine` version 2.3.0.  This ticket tracks removing the mapping code and traits in `mentat_parser_utils` in favour of `map_range` in `combine`.

**Comment by ncalexan** [comment]
I'll link to the relevant code snippets after #341 is reviewed and landed.

**Comment by eoger** [comment]
This was done in d1ac752de63508554c0212afffec47b348e2bf62.
