### ISSUE TITLE
[edn] Investigate surprising pattern matching behavior for unordered and unique value collections

### ISSUE THREAD

**Issue by victorporof** [mozilla/mentat#347]
The current pattern matching rules are tricky and surprising in certain cases, because the pattern matching "tokens" we've chosen are, in fact, symbols that obey the rules of the container collections they're a part of. This results in a rather leaky abstraction when it comes to pattern rules.

For example: `#{1 _ _}` cannot match `#{1 2 3}` because sets guarantee uniqueness of values, and since _ is just a symbol, the first set will have a length of 2, while the second one will have a length of 3. Maps follow a similar story, where: `{1 2, _ 4, _ 6}` cannot match `{1 2, 3 4, 5 6}` for the same reasons.

One can get around the above limitations by naming the "any operator" `_`:  `#{1 _a _b}` will match `#{1 2 3}` and `{1 2, _a 4, _b 6}` will match `{1 2, 3 4, 5 6}`. Support for this has been added in #338, however this approach might not be ideal. An alternative would be syntax support for patterns in the edn parser itself, where something like `#p _` would parse into a unique "any" pattern.

Another issue stems from matching named `?symbol`s in unordered collections. For example, when matching `#{?a ?b}` against `#{1 2}`, there's no clear definition for what `?a` and `?b` should end up being. Currently, assignment follows iteration order, which results in surprising (but consistent, not undefined) results where `#{?a ?b} =~ #{2 1}` has `?a` = 1 and `?b` = 2. This needs to be investigated, and if no solution found, consider outlawing such cases.

**Comment by rnewman** [comment]
Careful: the solution to this turns into building a Prolog interpreter. This is a constraint satisfaction problem: you're trying to define a set of constraints (in undecorated EDN, for some reason), and check whether an input document meets them.

**Comment by ncalexan** [comment]
I've tried to use the existing pattern matching in initial work in #271.  The issue under discussion here immediately raises it's head, and shows that greedily binding placeholder values can never work.  However, I'd like to avoid doing anything fancy (i.e., backtracking or other SAT solving strategies) entirely.  For the tests I have currently written, it's possible to:

1. Order the values being matched out of the store, by sorting by `[e a v tx added]` in some way.  The details of the order are less important than being deterministic.
1. Never pattern match `Value::Set` instances: that is, only match `Value::Set` instances literally.
1. Never pattern match the _keys_ of `Value::Map` instances: that is, only match `Value::Map` key instances literally.  Pattern matching the _values_ of `Value::Map` instances is pretty much required.

This simplifies the matcher significantly.

**Comment by joewalker** [comment]
> 1. Order the values being matched out of the store, by sorting by [e a v tx added] in some way. The details of the order are less important than being deterministic.

If I understand correctly, you're saying that `[3 ... 1] ~= [1 2 3]`? I get that we could see `#{3 ... 1} ~= {1 2 3}`, but that seems less obviously true for vectors. I suspect I'm missing something here.

**Comment by ncalexan** [comment]
> If I understand correctly, you're saying that [3 ... 1] ~= [1 2 3]? I get that we could see #{3 ... 1} ~= {1 2 3}, but that seems less obviously true for vectors. I suspect I'm missing something here.

No, I'm saying that the thing that produces the `Value` to be pattern matched will ensure the collections are ordered (`Value::{Vector,List}`) and will order them deterministically, rather than having the pattern matching be clever.  That is, I'll produce `[[e a v tx added]]` rather than `#{[e a v tx added]}`, even though conceptually the set of datoms introduced in a transaction is unordered; and I'll impose an (arbitrary but consistent) ordering on the produced vector.

Does that make more sense?  What I want is to get us matching fixed prefixes and suffixes in ordered collections, so we can eagerly bind placeholder values (no backtracking!); and not to handle unordered collections in much generality.

**Comment by joewalker** [comment]
Early morning thought → `[1 2 ... 2 3] ~= [1 2 3]`. Match? I think it shouldn't, but getting that right will take thought.

**Comment by victorporof** [comment]
@joewalker That definitely shouldn't match. There's an extra 2 in the pattern vet that doesn't exist in the input vec.

**Comment by rnewman** [comment]
> Early morning thought → `[1 2 ... 2 3] ~= [1 2 3]`. Match? I think it shouldn't, but getting that right will take thought.

It shouldn't, in three ways:

- Precondition failed: concrete match element count larger than input vec. (4 > 3)
- Consume two, split: remaining elements fewer than remaining match elements (1 < 2)
- Reverse iterator over `[3]` can't match the sequence `[3 2]`.

You might be justified in worrying if one were to support multiple splits, in effect creating a sliding window constraint satisfaction, but even so I think this whole thing is possible and safe by sequential calls to `match` over slices, chaining bounds between them.
