### ISSUE TITLE
Make the edn parser properly handle `...` symbols

### ISSUE THREAD

**Issue by victorporof** [mozilla/mentat#352]
The `...` strings parses as three separate symbols at the moment, when it should be just one.

**Comment by rnewman** [comment]
I think it parses as a single symbol. The query parser relies on this, and it worked at the time…

https://github.com/mozilla/mentat/blob/ac724bb79dd305f8760c6e2f911753d683fd018e/query-parser/src/parse.rs#L117

**Comment by rnewman** [comment]
You're right — the query parser does rely on it, but the EDN parser doesn't do the right thing.

**Comment by rnewman** [comment]
I added an expected-fail test for this:

https://github.com/mozilla/mentat/pull/353/commits/aceb10fb596e91f74668bfb814b58f06f6b9d454

**Comment by rnewman** [comment]
85f3b79

Note that this commit *prevents* you from using `..` or `.foo.` (or even `foo.bar`) as a symbol. I think that's OK, and if we were to address that, we'd do it by making these productions more thorough.
