### ISSUE TITLE
Consider whether to map idents in query results

### ISSUE THREAD

**Issue by rnewman** [mozilla/mentat#355]
At present, if you select a column of `db.type/ref`, you will get a `TypedValue::Ref` on the way out — that is, an `entid`.

Datomic automatically translates refs with idents.

I'm not convinced that this is a good idea, for these reasons:

- Even in Datomic, applications are encouraged to use entids for performance-critical code. The more entities we keep in entid form, the more likely they are to still be entids when we use them in queries or on the wire; that helps perf.
- Automatic translation makes it more likely that rels or collections will be heterogeneous. If an entity doesn't have an ident, it'll appear as a numeric entid, mixed in with keyword idents. That's a slight bug risk, I think.
- It's unclear how we'd represent an ident. Is it a `TypedValue::Keyword`, just like any other keyword? Or should it be another type alongside `TypedValue::Ref`, denoting that it's not just a keyword but a known ident for an entity, preserving the entid?
  - But isn't that relationship only valid in the scope of a particular `DB`?
- Callers won't necessarily use the ident, or use it for every row. Automatic translation isn't free — not only does it require a lookup, but at present it also requires cloning — and so some of the time it will be redundant and wasteful.
- In Rust we're pretty much guaranteed to always have the `DB` (and thus an entid map) in a nearby scope when processing query results; moreso perhaps than in Clojure. Given the choice between having the query engine always process idents, or having application code do the same thing (or more efficiently, working with a ref!) at a more suitable time, I feel the Rusty thing to do is to do the cheap thing by default and make the less-cheap thing easy to do.

My proposal is to _not_ map by default, but provide a projection option to do so. Tools that exist principally to present data to the user, like query frontends, will flip that flag to `true`. Ordinary consumers will work with `entid`s until they need `ident`s.

Opinions, @ncalexan, @joewalker, @victorporof?

**Comment by ncalexan** [comment]
I'll add a few thoughts.

> It's unclear how we'd represent an ident. Is it a TypedValue::Keyword, just like any other keyword? Or should it be another type alongside TypedValue::Ref, denoting that it's not just a keyword but a known ident for an entity, preserving the entid?
> 
>     But isn't that relationship only valid in the scope of a particular DB?

Datomic fudges this, in a way that I haven't tried to fully understand.  Whenever you re-assert a `:db/ident`, the old `ident` alias hangs around (potentially forever?).  I don't know what Datomic does if you then assert a new `entid` with the old `ident` alias; presumably, it overwrites the old mapping.

I've been working on #294 and friends, and what to do in the face of reasserted `:db/ident` is relevant.  In the Clojure implementation, we didn't track outdated `ident` mappings, and it's certainly simplest to do the same here.  Two places this might be significant:
- when one schema fragment is migrated forward, but old consumers remain.
- when replicating transactions across devices.

I'd like to avoid having `TypedValue` reference or encode the surrounding Mentat metadata if possible.

I'm inclined to not map `TypedValue::Ref` to `TypedValue::Keyword` in the query projector, except for known attribute positions.  For what it's worth, I initially did this mapping in `db/debug.rs`, and I've rolled it back locally 'cuz it's irritating to have some idents and mostly entids in even the debug output.

I'm mildly positive on providing a query option to expose this to humans.

**Comment by rnewman** [comment]
> except for known attribute positions…

Remember that attributes can be retracted and reasserted, too. These idents are no different to any other kind. Strictly speaking, I don't think attributes even need idents…

I think I'm firming up on the idea that automatic ident mapping definitely shouldn't be the default, simply because it's both inefficient and incorrect. That does indeed leave just an opt-in choice.

**Comment by ncalexan** [comment]
> Remember that attributes can be retracted and reasserted, too. These idents are no different to any other kind. Strictly speaking, I don't think attributes even need idents…

They do not.  But it's really convenient to do this mapping.

**Comment by rnewman** [comment]
I think it's convenient in some cases — tests, mainly, but also serialization. But remember that the query engine doesn't really distinguish between `?a` and `?v`: indeed, you might have a query like

```
[:find ?a :where
 [:john :truth/believes ?a]
 [?x ?a 9]]
```

— is the addition of the second tuple sufficient to cause us to always ident-map `?a`? Is the ordering in the query relevant? Would we always map `?a` because its entity is present in the attributes map?

Further, the same issues apply to attributes as to any other ident: duplication/cloning, inefficiency when passing back into another query, inaccuracy if an attribute is renamed, and so on.

I suppose I view this as a kind of serialization choice — when processing results directly, it's actually more convenient and less buggy to do:

```rust
  match col {
    TypedValue::Ref(entid) => {
        if let Some(kw) = db.get_ident(entid) {
            // Efficiently do something with a shared keyword reference
```

than to handle the clones and split the handling of ident-bearing entities across the `::Keyword` and `::Ref` clauses.

But when serializing to EDN to go across the wire, I expect it _is_ convenient to resolve everything we can, trading copying strings for round-trips to resolve. That can be embedded in the output format converter, or it can be an additional phase.

**Comment by rnewman** [comment]
I think we've reached sufficient consensus that the query engine should not project mapped idents.
