### ISSUE TITLE
Transparently fail for unknown attributes

### ISSUE THREAD

**Issue by rnewman** [mozilla/mentat#36]
We know at query translation time whether an attribute is present in the store: one can't transact a datom that refers to an attribute not present in the schema, so if the query system sees `:foo/bar` and can't turn it into an entity ID, that clause cannot return results.

At this point we know that:
- A `not` clause can be eliminated.
- An `or` branch can be pruned.
- A regular conjoining clause will always return no results.

One might think of this as producing ⊤ and ⊥ clauses from ordinary clauses.

We can optionally warn in this case: perhaps you intended to refer to a different attribute. We should not throw, because your query might be intended to work over a heterogeneous store, and so part of the query might adapt to different schema.

**Comment by rnewman** [comment]
The behavior right now is that we call `(entid :foo/bar)` and get `:foo/bar` rather than `6`.

**Comment by rnewman** [comment]
… and I believe that causes the query to fail or hang; I'm not seeing happiness in my tests.

**Comment by ncalexan** [comment]
> The behavior right now is that we call (entid :foo/bar) and get :foo/bar rather than 6.

Perhaps we want an `entid-strict` to fail in cases when the ident is known?

**Comment by rnewman** [comment]
I'd rather see it return `nil` for unknown. One of the advantages Datomish has is to allow you to work with databases that aren't entirely known to you. That means having queries adapt, rather than fail — we might warn if a top-level pattern can't exist in this database (which means zero results for sure), but if an `or` branch isn't possible, then that's probably just an opportunity for pruning.

**Comment by rnewman** [comment]
This is handled correctly in #243.
