### ISSUE TITLE
Check SQLite version on first use

### ISSUE THREAD

**Issue by rnewman** [mozilla/mentat#366]
We use some features with minimum SQLite version support, such as partial indices (3.8.0).

rusqlite recently grew `version` and `version_number` functions. We should use those in `db/src/db.rs` to verify that we can use the linked SQLite library before going any further.

**Comment by fluffyemily** [comment]
I've hit a bit of a snap with this one. I tried adding a new error to `db.src.errors.rs` for the incorrect minimum SQLite version, but hit the error `recursion limit reached while expanding the macro 'quick_error'`. A brief google shows that this is an issue [we have hit before](https://github.com/brson/error-chain/issues/117), and that there are [no current plans to resolve this](https://github.com/dtolnay/quote/issues/15).

It also suggests adding `#![recursion_limit = "128"]` to the crate. I note that in the issue @ncalexan raised ([#177](https://github.com/brson/error-chain/issues/117)) he mentions that this made no difference, and I have tried the same thing, also to no effect.

Did we find a way to get around this? Is do, what was it? If not, how should I add a new error type?

**Comment by rnewman** [comment]
Can you reuse an existing error? We already do some kind of check on open, right?

Can you just panic instead? After all, if we are linked against the wrong SQLite version, it's an unrecoverable error. Better to die hard on open than nothing at all, so that would be my chosen fallback behavior.

**Comment by rnewman** [comment]
Also see if there's a new release of error chain that we could upgrade to if it fixes their issue.

**Comment by fluffyemily** [comment]
> Also see if there's a new release of error chain that we could upgrade to if it fixes their issue.

There has been no release of error chain since 20th Nov last year.

**Comment by fluffyemily** [comment]
> Can you reuse an existing error? We already do some kind of check on open, right?

None of the existing errors really fit - they're all too specific for our purposes. I think the panic is the best option here.

**Comment by ncalexan** [comment]
Hi @fluffyemily , sorry I haven't communicated what the plan is here.  I intend to extract a few `Error` enum types out of the `error-chain` soup, and then have the `ErrorKind` refer to those types.  I think @rnewman is doing similar in some of the `query-*` crates.

@fluffyemily feel free to use `NotImplementedError`, even though it doesn't really make sense.  That'll get cleaned up as and when we get to the real `error-chain` clean-up.
