### ISSUE TITLE
[tx] Handling retracting schema characteristics, like `:db/cardinality` and `:db/unique`.

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#379]
After #370 (fixing #294 and #295), we still need to implement handling `[:db/retract :attribute :db/* ...]` of schema characteristics.  This might also address `[:db/retractEntity :attribute]` if it comes after https://github.com/mozilla/mentat/issues/378.

The tricky thing to ensure here is that we fall back to the default correctly, and that the "schema" materialized view does not get out of sync with the in-memory state.

**Comment by rnewman** [comment]
Fixed!
