### ISSUE TITLE
Parse :not and :not-join

### ISSUE THREAD

**Issue by rnewman** [mozilla/mentat#389]
Part of #239.

**Comment by fluffyemily** [comment]
Examples of Not and Not Join from Datomic. Do we want to match this here?

Not
```
[:find ?name
 :where [?eid :artist/name ?name]
        (not [?eid :artist/country :country/CA])]
```

Not-join
```
[:find (count ?artist) .
 :where [?artist :artist/name]
        (not-join [?artist]
          [?release :release/artists ?artist]
          [?release :release/year 1970])]
```

**Comment by fluffyemily** [comment]
The Datomic docs on not have pretty much exactly the same wording as for or and so we probably need to validate in the same way.

* unify the variables. 
    * In `not` that means ensuring that any variable in the not clause is also represented in the other clauses (`?eid` in the example above). 
    * In `not-join`, ensuring that the variables stated in the join list (`?artist` in the example above) are represented in the other clauses.
    * In the `not-join` that the variables in each leg of the not match (`?release` in the example above`)

**Comment by rnewman** [comment]
> Do we want to match this here?

Yes.


Validation and variable extraction of `or`, which you can reuse here, are in #394; I hope to land those today.

Note that `not` doesn't have legs/arms in the way that `or` does. `not` and `not-join` simply have a _body_, so there's no analogue of making sure that each arm is similar. That's nice.

Algebrizing simple `not` is pretty much equivalent to computing the non-negated changes, wrapping them in a negation, and adding them to the destination CC.

Algebrizing simple `not-join` with non-exhaustive unification is much the same, but of course bearing in mind the vars that aren't allowed to unify!

Algebrizing complex `not` — clauses that themselves contain a complex join or generate bindings — involves adding `NOT EXISTS` to the final query.

https://github.com/mozilla/mentat/blob/master/src/common/datomish/query/clauses.cljc#L178

and

https://github.com/mozilla/mentat/blob/master/src/common/datomish/query/clauses.cljc#L300

and

https://github.com/mozilla/mentat/blob/master/src/common/datomish/query/clauses.cljc#L323

should be a pretty good inspiration.

The algebrizing part will be much easier with my `or` work to follow, so I recommend you start with parsing once you're satisfied that you understand the concepts!

**Comment by fluffyemily** [comment]
Do we have to take into account Not And and Not Or?

**Comment by rnewman** [comment]
Yes! The grammar is here:

http://docs.datomic.com/query.html

But the CLJS implementation already gets this right, I think.

**Comment by fluffyemily** [comment]
For validation purposes, I need to ensure that variables mentioned in the `not` clause are the same ones that are mentioned in the other where clauses (in the example above, `eid`). At the point at which we are validating for `or`, we only have access to the current clause and those it contains. How do I gather the collection of variables for the `not`'s sibling clauses to validate them against?

**Comment by rnewman** [comment]
`apply_not_clause` is a method on CC. At that point you can say `self.column_bindings.keys()` (and similar for input bindings) to get iterators over known variables.

**Comment by rnewman** [comment]
There is a validation step that only requires the `NotJoin`, and that's validating explicit unify vars against the clause itself. To do that you'll need to duplicate some of the var extraction code from the last or-join work I landed.

**Comment by fluffyemily** [comment]
OK, cool. I was trying to do the CC `apply_not_clause` validation inside the `NotJoin` validation. Makes more send this way. I'll just stick with what I've got then.

**Comment by fluffyemily** [comment]
https://github.com/mozilla/mentat/commit/bd389d2f0de395ef1bc46ea4363def098e2bd687
