### ISSUE TITLE
Set up a first benchmark

### ISSUE THREAD

**Issue by bgrins** [mozilla/mentat#406]
AIUI a good first candidate for benchmarking might be the tx-parser: https://github.com/mozilla/mentat/blob/rust/tx-parser/tests/parser.rs.

There's built in support for benchmark tests: https://doc.rust-lang.org/book/benchmark-tests.html, so let's try to use them if possible.

**Comment by bgrins** [comment]
After adding a benchmark test for tx-parser, it can be run with `cargo bench --package mentat_tx_parser`

**Comment by bgrins** [comment]
@ncalexan wanted to get some feedback on the approach here before opening a PR.

1) Any opinion on whether to incorporate these in the code or an external folder?  Here's some code that does [benchmarks in-file](https://github.com/mozilla/mentat/compare/rust...bgrins:initial-benchmarks?expand=1) and here's some that does [benchmarks in a separate file](https://github.com/mozilla/mentat/compare/rust...bgrins:initial-benchmarks-2?expand=1).  I'm leaning towards the latter myself so that we could see all benchmarks in one place, but I'm not sure if there's a criteria you've been using for when a test should be inline vs external that might be relevant here.
2) Any opinion on what to actually benchmark? Both examples above use the same code which I sniped / modified from some of the tests in `tx-parser/src/lib.rs` and are basically running `Tx::parse` through a situation with a small and large sample of edn.

**Comment by ncalexan** [comment]
> @ncalexan wanted to get some feedback on the approach here before opening a PR.
> 
>     Any opinion on whether to incorporate these in the code or an external folder? Here's some code that does benchmarks in-file and here's some that does benchmarks in a separate file. I'm leaning towards the latter myself so that we could see all benchmarks in one place, but I'm not sure if there's a criteria you've been using for when a test should be inline vs external that might be relevant here.

Slight preference for external folder (`benches`?), like we have `tests` (for some things).

>     Any opinion on what to actually benchmark? Both examples above use the same code which I sniped / modified from some of the tests in tx-parser/src/lib.rs and are basically running Tx::parse through a situation with a small and large sample of edn.

This useful, for sure.  I've been thinking of the combinatorial product of:

* {N assertion,N retraction} for N=1,2,3,4,5,10,50,500,5000
* `:db/cardinality :db.cardinality/{one,many}`
* {`:db/unique :db.unique/identity`} where it makes sense

Into an empty store, and into a store with N=1,10,100,1000,10000,...1e6 existing datoms/transactions.

**Comment by bgrins** [comment]
> Slight preference for external folder (benches?), like we have tests (for some things).

Sounds good to me, I'll proceed with that branch.
