### ISSUE TITLE
[query] Implement a shareable counter for multi-CC aliasing

### ISSUE THREAD

**Issue by rnewman** [mozilla/mentat#407]
We often produce a _template_ from an existing CC, use it to build a bunch more CCs, and then combine them.

For all such uses apart from a simple `or`, the 'receptacle' CCs need to allocate their own table aliases, and they mustn't collide with each other or the template/parent.

This issue tracks altering our aliasing mechanism to use a shared counter.

**Comment by rnewman** [comment]
@ncalexan: take a look at

e8950d1ce3b08e3f9369ebd61fac0e2a67ccc60a
97895da29f95b80a9f3fee78c05cee0ffc150822

**Comment by ncalexan** [comment]
> @ncalexan: take a look at
> 
> e8950d1
> 97895da

I'm OK with this.  I had some nits and a request for a comment.

**Comment by rnewman** [comment]
Landed in #407.
