### ISSUE TITLE
[query] Implement ordering

### ISSUE THREAD

**Issue by rnewman** [mozilla/mentat#415]
For Mentat I think I'd like to do this by extending syntax:

```
[:find ?x ?v
 :in $
 :where [?x :foo/value ?v]
 :order (:desc ?v)]
```

… with the obvious future extension of putting `:limit` into the query format, too. It seems nonsensical to add another out-of-band signaling method, particularly one that has to agree with the contents of the query.

**Comment by ncalexan** [comment]
I concur.  There are several tweaks to Datomic's syntax that we should feel free to make.

**Comment by rnewman** [comment]
TODO: we do this by projecting variables, just like `:with`. We also need to project type tags and order on those… which means defining an ordering of types.

**Comment by rnewman** [comment]
#416!

**Comment by rnewman** [comment]
35d73d5
