### ISSUE TITLE
[tx] Speed up transaction parser

### ISSUE THREAD

**Issue by bgrins** [mozilla/mentat#436]
When importing a map structure via transactions that contains around 1000 lines I'm getting around 3 seconds on the parse

<img width="1031" alt="mentat-profile" src="https://cloud.githubusercontent.com/assets/95570/25508533/89bdfd94-2b67-11e7-8508-5b7635e68a66.png">

**Comment by bgrins** [comment]
From slack:

> Nice thing is it's trivially parallel
> Mmap the file, segment lines, pass offsets to parser, preprocess in parallel, queue for final write

**Comment by rnewman** [comment]
Though I should add: it's theoretically possible for us to parse this data with zero string copying, and it should be way faster than this, even serially. It might be a lot of work to get there, but it seems wiser to do some of it than to immediately throw cores at the problem!
