### ISSUE TITLE
[query] Support tx places in queries

### ISSUE THREAD

**Issue by rnewman** [mozilla/mentat#440]
Right now we only allow placeholders in patterns, so you can't write:

```
[:find ?tx :where [?x ?a "foo" ?tx]]
```

See `constrain_to_tx` and `apply_pattern_clause_for_alias`, and the test in `tests/query.rs`.

**Comment by fluffyemily** [comment]
@rnewman 
Currently `[:find ?name :where [?x :foo/name ?name ?tx]]` with `?tx` provided a value in the inputs returns the most recent value associated with the attribute, not the one associated with the transaction id. 

Does this bug also include enabling this?

**Comment by fluffyemily** [comment]
Ignore previous comment. Was forgetting to add `:in`.
