### ISSUE TITLE
Make it possible for consumers to depend on only the mentat crate (no mentat_db or mentat_core, for example)

### ISSUE THREAD

**Issue by bgrins** [mozilla/mentat#443]
As an example, I'm needing to depend on mentat_db and mentat_core here: https://github.com/bgrins/neon-mentat/blob/master/native/Cargo.toml#L17-L19.  They are used for connecting and then processing results in https://github.com/bgrins/neon-mentat/blob/master/native/src/lib.rs.

We should make it easier to vendor by exposing any public API through the root mentat crate.

**Comment by rnewman** [comment]
059b9d1
