### ISSUE TITLE
[edn] Speed up EDN parser

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#445]
Our `rust-peg` derived parser seems very slow; this ticket tracks speeding it up.  After #436, I see us spending 5.31s (!) parsing some of the example EDN @bgrins pushed (compared to ~450ms in `tx-parser` and ~400ms to actually transact the resulting assertions).

**Comment by kevinmehall** [comment]
Where can I find example input that is slow to parse? I'd be happy to take a look and help optimize, whether it's something in your grammar or something in rust-peg.

**Comment by ncalexan** [comment]
> Where can I find example input that is slow to parse? I'd be happy to take a look and help optimize, whether it's something in your grammar or something in rust-peg.

@kevinmehall we'd love some help.  The relevant tree is https://github.com/ncalexan/mentat/tree/bgrins-could-not-search/

The relevant subcrate is `edn` and the grammar is at https://github.com/ncalexan/mentat/blob/bgrins-could-not-search/edn/src/edn.rustpeg.  EDN is conceptually similar to JSON, albeit slightly richer.

I've been using `Instruments.app` to profile on Mac OS X.  The file we're parsing is 780k and not particularly deeply nested: https://github.com/ncalexan/mentat/blob/bgrins-could-not-search/tests/music-data-partial.dtm

**Comment by ncalexan** [comment]
> I've been using Instruments.app to profile on Mac OS X. The file we're parsing is 780k and not particularly deeply nested: https://github.com/ncalexan/mentat/blob/bgrins-could-not-search/tests/music-data-partial.dtm

I've been profiling some test code, which may not be getting the optimization passes that `rust-peg` derived parsers need to be performant.  I'll try to verify that the bits getting profiled are in fact built in release mode, and then I'll dig deeper into the generated code and bottlenecks.

**Comment by kevinmehall** [comment]
I have to assume the 5.31s is without Rust optimization enabled (`cargo --release`). I'm seeing about 170ms for that file with rust-peg 0.5.3 on my laptop (Haswell i5-U).

I have some tweaks to the grammar here that bring that down to about 100ms:
https://github.com/ncalexan/mentat/compare/bgrins-could-not-search...kevinmehall:peg-optimize
That is off of the bgrins-could-not-search branch, so let me know if you would like me to rebase on master and submit a PR.

This pending change to rust-peg brings it down to about 33ms:
https://github.com/kevinmehall/rust-peg/pull/166

**Comment by rnewman** [comment]
For the record: performance problems do indeed mostly disappear when you run in release mode!
