### ISSUE TITLE
Start mentat server as CLI starts

### ISSUE THREAD

**Issue by fluffyemily** [mozilla/mentat#451]
When the CLI starts, a mentat server should be started and accessible from the CLI.

**Comment by rnewman** [comment]
IMO we shouldn't be doing this over a connection: the CLI should be opening and closing DBs directly, performing operations through the Rust API.

**Comment by fluffyemily** [comment]
When I wrote this I was looking at `src/main.rs` and thinking this is the way to do it, but now I'm looking at it I realise that is the wrong way to go. Closing this ticket as https://github.com/mozilla/mentat/issues/452 should cover it all.
