### ISSUE TITLE
Accept mentat commands from inside CLI

### ISSUE THREAD

**Issue by fluffyemily** [mozilla/mentat#453]
* Determine if a mentat command is being entered. A mentat command starts with a `[` or `{` and encompases everything typed until a matching `]` or `}` is entered, at which point the command is ready executed.
* Examine the entered command before execution and determine if it is a query (`:find`) or a transaction (everything else).

**Comment by rnewman** [comment]
Do bear in mind that technically `[:where [?x :foo/knows ?y] :find ?y]` is valid, so we can't just check the first symbol.
