### ISSUE TITLE
Execute mentat commands from a file

### ISSUE THREAD

**Issue by fluffyemily** [mozilla/mentat#456]
* Accept file path as argument to CLI tool. 
* Implement `.read` command that takes a filepath as an argument
* open and read file.
* execute all commands inside file after required DB has opened.
* Do not accept further input until all commands have finished executing.
* Stop execution of commands at first error generated by a read command.

Question: Should any executed transactions from the file be retracted if an error occurs?

**Comment by rnewman** [comment]
Fixed in #553 for transact.
