### ISSUE TITLE
Provide a quit command

### ISSUE THREAD

**Issue by fluffyemily** [mozilla/mentat#457]
* Typing `.q`, `.quit` or `Ctrl+D` should exit the CLI tool. 

Question: If a command is being executed when Ctrl+D is entered, the CLI should quit only once the transaction has completed? Or should it cease execution at the point of interruption? If cease execution, how do we achieve that?

**Comment by rnewman** [comment]
Perhaps we should block while a command is running? Doesn't make sense to have two commands running…

**Comment by fluffyemily** [comment]
`.q` has been taken as a short command for running queries. Renaming to `.exit` and `.e`
