### ISSUE TITLE
Cannot start server on Linux AMD64

### ISSUE THREAD

**Issue by blak3mill3r** [mozilla/mentat#464]
I carefully followed the instructions at https://github.com/mozilla/mentat/blob/rust/README.md#building 

```bash
$ git status
On branch rust
Your branch is up-to-date with 'origin/rust'.
```

`cargo build` and `cargo test --all` apparently worked fine... however:

```bash
$ cargo run serve
error: a bin target must be available for `cargo run`
```

Are the instructions outdated? Did I do something wrong?

**Comment by blak3mill3r** [comment]
```
cargo --version
cargo 0.18.0 (fe7b0cdcf 2017-04-24)
```

just installed rust in order to try out mentat, using https://www.rustup.rs/

**Comment by rnewman** [comment]
Hi!

The instructions are outdated. #448 just moved the stub server code out of the main path to help minimize footprint. 

Right now the minimal Rust API, using `Conn`, as expressed in the top-level tests, is the best way to try this out. 

I'll keep this issue open to track fixing the docs. 

Thanks!

**Comment by rnewman** [comment]
Fixed in https://github.com/mozilla/mentat/commit/953f9f773496f5c63d76a2cba60e43b8d68dd7f5.

**Comment by blak3mill3r** [comment]
Thanks! Do I understand correctly that Mentat currently only implements a Rust library which provides a data store embedded in a Rust project?

(AOT querying a Mentat server with EDN over TCP or similar?)

**Comment by ncalexan** [comment]
> Thanks! Do I understand correctly that Mentat currently only implements a Rust library which provides a data store embedded in a Rust project?

That's the principle vehicle, but @fluffyemily is building a CLI to expose a human-oriented interface over in https://github.com/mozilla/mentat/projects/3, and it would be easy (if not something we'll do anytime soon) to expose `/transact` and `/query` endpoints via an HTTP/Socket service.
