### ISSUE TITLE
Clarify that the Rust branch is the active branch

### ISSUE THREAD

**Issue by jryans** [mozilla/mentat#468]
The README for the `rust` branch (which is the default in GitHub) says "This branch is for rewriting Mentat in Rust". 

It might be better to rewrite this text, since it seems like the Rust version is where all the work happens. It "is" the project now, not an experiment.

**Comment by bgrins** [comment]
I believe @rnewman was planning to rename the current master branch to something else and then rename the rust branch to master

**Comment by rnewman** [comment]
Done. `master` renamed to `clojure`, and `rust` copied to `master`.

This is equivalent to a force-push to `master`, so you might need to fiddle with git a little.

Thanks for the poke, @jryans!

**Comment by jryans** [comment]
@rnewman Thanks! Looks like the repo settings still default to displaying the `rust` branch, I guess this should also be changed to `master`?

**Comment by rnewman** [comment]
Forgot to click "Update" on that screen. Thanks!
