### ISSUE TITLE
[sync] HTTP client for uploading transactions

### ISSUE THREAD

**Issue by grigoryk** [mozilla/mentat#509]
Tolstoy needs to be able to upload a set of local transaction to a remote server.

Prototype will revolve around server API as described in https://github.com/rfk/mentat-sync-prototype/

An upload looks something like:

```
For each outgoing transaction:
    Locally construct the appropriate set of chunks
        For each chunk:
            Upload it via PUT /chunks/{chunk}
        Upload transaction metadata via PUT /transactions/{trn}
    Make the final transaction the new head via PUT /head
        This will be rejected if it doesn't descend from the current head
        If rejected due to concurrent change, abort and (eventually) resync
```

Representing a transaction as a series of chunks is, in this context, `transaction serialization`.

**Comment by rnewman** [comment]
@eoger has been thinking a bit about a Rust FxA client. It'd be nice if our HTTP stories converged.

**Comment by rnewman** [comment]
@grigoryk I think it's worth having a separate issue for encoding tx chunks. They will have some amount of metadata, and we also need an HMAC and other mechanisms for ensuring that what we upload makes sense — robustness and tamper-resistance.

**Comment by grigoryk** [comment]
Done in #543
