### ISSUE TITLE
[sync] Raw transact

### ISSUE THREAD

**Issue by grigoryk** [mozilla/mentat#512]
Tolstoy needs to be able to assert datoms derived from a set of (inserted) remote transactions.

**Comment by rnewman** [comment]
There are two definitions of this:

1. Just like normal `transact`, but with the `txInstant` specified (which is an [open TODO](https://github.com/mozilla/mentat/blob/master/db/src/tx.rs#L637)) and a fixed tx ID (which is a [function parameter](https://github.com/mozilla/mentat/blob/rnewman/simple-schema/db/src/tx.rs#L153)).
2. Bypassing all of the expensive upsert, tempid, etc. mechanics that most of `transact` does. We're in the process of adding `transact_terms`, which is closer, but this would be an even lower layer, transacting `TermWithoutTempIds` — which touches on #508, as `TermWithoutTempIds` _is_ `Term<KnownTempId, TypedValue>`, a raw representation of a datom.

**Comment by grigoryk** [comment]
Completed in #563. Not in the most optimal way, but it works.
