### ISSUE TITLE
hello, I would like to collaborate with your project living from translator to Spanish which is my native language

### ISSUE THREAD

**Issue by LuigiBaute** [mozilla/mentat#549]

**Comment by rnewman** [comment]
Hi Luigi! What kind of work are you looking to do?

**Comment by LuigiBaute** [comment]
I can provide translations of any PR with over a thousand words (to be translated). Don't worry I'll ask each time for 'permission to proceed' on the PR I find interesting, right now I was thinking about README file, What do you think?

**Comment by rnewman** [comment]
That would be fine by us, Luigi; we are happy to have your contributions, if you are willing to spend the time!
