### ISSUE TITLE
Support connection listeners

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#61]
Datomic and DataScript show a simple API for listening to transactions.  We'll want something similar, in particular to allow the UAS to listen for changes and propagate diffs out to clients.

**Comment by rnewman** [comment]
jkerim was also mentioning how AS is (or wants to be) structured like a modern app service — lots of worker tasks pushed off to be run in the background in response to streams of data. The closer we can get to that model, the more composable this system will be.

**Comment by rnewman** [comment]
@fluffyemily is this done?

**Comment by fluffyemily** [comment]
@rnewman I'd say so.
