### ISSUE TITLE
Enable Rust library to be built with bitcode on iOS

### ISSUE THREAD

**Issue by fluffyemily** [mozilla/mentat#611]
Currently, building on Xcode with bitcode enabled fails as the Rust library is not built Bitcode compatible. This issue tracks enabling the library to be build with Bitcode enabled so we don't force iOS developers to disable Bitcode on their apps.

**Comment by fluffyemily** [comment]
https://github.com/alexcrichton/rust/commit/d2855b06c874f0a6f2a3ce990fbd608a76b7c88b?diff=unified

**Comment by rnewman** [comment]
This was actually merged:

https://github.com/rust-lang/rust/commit/3b6412b94324b10f698a18ea5766ef6ff8921ae8

**Comment by fluffyemily** [comment]
Yes, I think if we upgrade our Rust version we will get bitcode for free
