### ISSUE TITLE
Logo + Name?

### ISSUE THREAD

**Issue by apavlo** [mozilla/mentat#715]
I have added an entry for Mentat in my encyclopedia of databases:

https://dbdb.io/db/project-mentat

I have two questions:

1. Is there a logo for 'Project Mentat'?

2. Is the name of the database 'Project Mentat' or just 'Mentat'?

Thanks.

-- Andy

**Comment by ncalexan** [comment]
Hi Andy, thanks for adding us.

> Is there a logo for 'Project Mentat'?

We got a little ways down this path in https://github.com/mozilla/mentat/issues/348 but haven't committed.

> Is the name of the database 'Project Mentat' or just 'Mentat'?

Let's say "Mentat".  The project appellation was a little piece of Mozilla politics that doesn't seem quite so relevant now.

Thanks again!
