### ISSUE TITLE
Gradle task for publishing Android SDK to jcenter/bintray

### ISSUE THREAD

**Issue by grigoryk** [mozilla/mentat#718]
Getting mentat SDK onto jcenter (for now probably a temporary bintray repo) would let other project use the SDK as simply as...

`implementation "org.mozilla.mentat:mentat:{latest-version}` - exact naming TBD.

**Comment by ncalexan** [comment]
This is definitely a good idea.  See also #695.  I imagine there are several "Rust + FFI + mobile platforms" projects that would all like to do this, so establishing some patterns would be nice.

**Comment by grigoryk** [comment]
There's `android-components`, which is publishing stuff under `org.mozilla.components`.

Related: https://github.com/mozilla-mobile/android-automation-tools
