### ISSUE TITLE
Is this project stable? Language support?

### ISSUE THREAD

**Issue by robehickman** [mozilla/mentat#719]
Hi,

I'm inspired by the ideas that datomic puts forward, but it is too expensive and probably overcomplicated for my needs. Mentat looks interesting but is it stable, and is it possible to use it in languages besides Rust? If I was going to use it, it would be from PHP.

**Comment by ncalexan** [comment]
> I'm inspired by the ideas that datomic puts forward, but it is too expensive and probably 
overcomplicated for my needs.

This is somewhat true for our needs (at Mozilla), although we have a larger issue: Datomic is intended to be distributed as a client/server and we need an embedded store.

> Mentat looks interesting but is it stable,

No.  We're actively building core functionality, and nothing at Mozilla (or elsewhere) is shipping based on it.  We won't be entering anything like stability for a long time (Q1 2019 at the earliest).

We basically have no documentation of what's implemented, let alone what's specific to Mentat, so you have to be willing to really dig into the internals to solve problems.

> and is it possible to use it in languages besides Rust? If I was going to use it, it would be from PHP.

It's possible -- we're building FFIs for Swift and Java as part of our requirements -- but we wouldn't be doing anything specifically for PHP.  But, if PHP can invoke "standard" FFI mechanisms (C names, standard stack conventions) you should be able to use the FFI more-or-less directly.  Nothing like trying it out to see what's possible and whether the project's maturity is suitable for you.

**Comment by robehickman** [comment]
Another thought. With regards to using SQLite, would there be anything to be gained by dispensing with SQL and using lower level constructs directly? This is something that I've always found to be a pain, either you have flat files and have to do absolutely everything yourself, or you have SQLite and have to force everything into the model that SQL presents. There isn't any middle ground that I am aware of.

**Comment by rnewman** [comment]
@robehickman there is no stable internal API for SQLite’s data formats, and I think it would take significant expertise to use the internal functions.

If we were to dispense with SQL we would likely switch to managing blocks of data ourselves, perhaps on top of LMDB via rkv.
