### ISSUE TITLE
Code style: standardize `<` prefix and `!` suffix

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#72]
This is strictly a code style concern.  Right now, we're sloppy in our naming -- sometimes things that return pair channels are prefixed `<` (good) and sometimes not (bad).  Likewise, sometimes things that write to a resource are suffixed `!` (good) and sometimes not (bad).

**Comment by rnewman** [comment]
Bulk-closing ClojureScript/Datomish tickets.
