### ISSUE TITLE
lookup-ref syntax is different between Mentat and Datomic

### ISSUE THREAD

**Issue by thomcc** [mozilla/mentat#812]
This doesn't seem to be documented anywhere (or maybe I'm misread the datomic docs?), but is probably worth mentioning somwhere.

According to https://docs.datomic.com/on-prem/identity.html and http://blog.datomic.com/2014/02/datomic-lookup-refs.html Datomic does them as `[:namespace/attr value]`, whereas we do it as `(lookup-ref :namespace/attr value)`.

I'm filing an issue rather than just updating https://github.com/mozilla/mentat/wiki/Differences-from-Datomic because i'm actually not 100% certain it's not me misreading the datomic docs, or failing to interpret what we do.

**Comment by rnewman** [comment]
#666, #392. The use of `(lookup-ref …)` is to eliminate ambiguity, and that's discussed in those tickets. Datomic isn't very well documented, and implementing Mentat in Rust exposed a number of the ambiguities that Clojure glosses over.

**Comment by thomcc** [comment]
Yeah, I can see that it avoids some syntactic ambiguity. I've documented it on the wiki even though there's an issue open to fix it.
