### ISSUE TITLE
Improve speed of [a v] lookups

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#90]
Right now, `<avs` does a bunch of selects against `all_datoms`.  It's super slow, since it's extremely inefficient to query`all_datoms` for a textual match.  This ticket tracks doing something less significant than #69 to speed this up.  Namely:
- only query from `all_datoms` for fulltext attributes;
- consider using a temporary table and one big query rather than many small queries.

**Comment by rnewman** [comment]
@ncalexan is this still relevant with your rewrite?

**Comment by ncalexan** [comment]
No, this should be "efficient" if not "optimized".
