### ISSUE TITLE
Optimize bulk id-literal insert: allocate tempids without iterating and using an atom

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#92]
This is follow-up to #88.  Do the work from https://github.com/ncalexan/datomish/pull/1#discussion_r83296618 in one collect-and-advance, rather than iterating.  I expect this will allow us to drop, or simplify, the part-map atom in the connection.

**Comment by rnewman** [comment]
@ncalexan still valid?

**Comment by ncalexan** [comment]
Nope, I think we're pretty efficient now!
