### ISSUE TITLE
Route tx-meta through `<transact!` into listeners and possibly the tx-report

### ISSUE THREAD

**Issue by ncalexan** [mozilla/mentat#93]
This is just a handy way to connect transactors and listeners.

One use case: the UAS transacts a bookmark star, associates the HTTP request with the transaction, and a listener fires off WebSocket diff messages, using a logger/identifier associated with that HTTP request.

One reason to not include `tx-meta` directly in the `tx-report`: not all useful metadata can be (or should be) serialized over the wire to consumers.  (For example, request loggers!)

**Comment by rnewman** [comment]
Closing this; we'll be re-addressing tx listeners as we build that for Rust.
